export const SET_TOKEN = "SET_TOKEN"
export const LOGOUT = "LOGOUT"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const CLEAR_LOGIN_ERROR = "CLEAR_LOGIN_ERROR"
export const SET_USER_TYPE = "SET_USER_TYPE"