export const SERVICES_ADDED_SUCCESSFULLY = "SERVICES_ADDED_SUCCESSFULLY"
export const CLEAR_SERVICES_ADDED_SUCCESSFULLY = "CLEAR_SERVICES_ADDED_SUCCESSFULLY"
export const SERVICES_LIST = "SERVICES_LIST"